name: Test and Build
on:
  push:
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.32
        args: -v -D errcheck
    - name: goimports
      run: go get golang.org/x/tools/cmd/goimports && make goimports-check
    - name: code coverage
      run: make cover-ci
    - name: upload codecov
      run: bash <(curl -s https://codecov.io/bash)
    - name: go build
      run: make build