name: Test and Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.39
        args: -v --timeout=5m
    - name: goimports
      run: go get golang.org/x/tools/cmd/goimports && make goimports-check
    - name: go test
      run: make test-ci
    - name: update code coverage badge
      run: make update-code-coverage-badge
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
    - name: go build
      run: make build